config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  # second root. This route is used when user logs in
  get '/restaurants' => 'restaurants#index'
  get '/restaurants/favourites' => 'restaurants#favourite'

  # facebook callback
  get '/auth/:provider/callback' => 'sessions#create', as: :omni_auth

  # LOG IN
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # Add recipe to dish
  post '/dishes/:dish_id/add_recipe/:id' => 'recipes#add_recipe', as: :add_recipe 
  delete '/dishes/:dish_id/remove_recipe/:id' => 'recipes#remove_recipe', as: :remove_recipe


  resources :users do
    resources :favourites, only:[:create, :destroy] 
    resources :menus, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :menus, only:[] do
    resources :dishes
  end
  
  resources :recipes do
    resources :ingredients
  end 
  
  resources :preferences, only: [:show, :edit, :update]
  
  # takes out the ingredient to recipe but does not delete the ingredient itself
  delete '/recipes/:recipe_id/remove_ingredient/:ingredient_id/' => 'inclusions#destroy', as: :inclusion

  # like or unlike a dish
  post 'dish/:dish_id/add_like/:user_id' => 'likes#create', as: :like
  delete 'dish/:dish_id/remove_like/:user_id' => 'likes#destroy', as: :unlike
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user
    
  # has_many :menu_dishes, dependent: :destroy
  has_many :dishes, dependent: :destroy

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController 
  before_action :find_menu, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  respond_to :js 
  
  def index 
    @user = User.find params[:user_id]
    @menus = @user.menus.all
    @menu = Menu.new
  end 

  def new
  end

  def create
    @user = User.find params[:user_id]
    @menu = current_user.menus.new menu_params
    if current_user.is_admin
      if @menu.save
        respond_with()
        # redirect_to user_menus_path(@user)
      else
        render :new
      end 
    else
      flash[:alert] = "You dont have permissions to create a menu"
      redirect_to restaurants_path
    end
  end 

  def edit
  end 

  def update
    @user = User.find params[:user_id]
    if @menu.update menu_params
      redirect_to user_menus_path(@user)
    else
      render :edit
    end
  end 

  def destroy
    @user = User.find params[:user_id]
    if @menu.destroy
      respond_with()
      flash[:alert] = "Menu deleted"
      #redirect_to user_menus_path(@user)
    else
      flash[:alert] = "Unable to delete menu"
    end
  end 


  private

  def menu_params
    params.require(:menu).permit(:name)
  end 

  def find_menu
    @menu = Menu.find params[:id]
  end 

end 

app/views/menus/_form.html.erb
<%= simple_form_for [current_user, @menu], remote: true do |m| %> 
  <%= m.input :name %>
  <%= m.submit %>
<% end %>

app/views/menus/_new.html.erb
<%= render "form" %>

app/views/menus/_row.html.erb
<div id="<%= dom_id(menu)%>">
  <h1 class="menu_name" ><%= menu.name %></h1>
  <% if user_signed_in? && (current_user == @user) %>
    <%= link_to "Edit", edit_user_menu_path(@user, menu) %>
    |
    <%= link_to "Delete", user_menu_path(@user, menu), method: :delete, remote: true, data: {confirm: "Are you sure?"}  %>
    |
    <%= link_to "Add Dish", new_menu_dish_path(menu.id) %>    
  <% end %>

  <div class="row row__ingredients_index">
    <% count = 0 %>
    <% menu.dishes.each do |dish| %>
      <div class="col-md-6">
          <% if user_signed_in? && !current_user.is_admin && (current_user.allergic_to?(dish) || current_user.diet_restriction?(dish)) || current_user.find_by_description(dish) %>
            <div class="well allergy" style="display:none;">
              <%= render partial: 'dishes/index', locals: {dish: dish, menu: menu} %>
            </div>
          <% else %>
            <div class="well dish">
              <%= render partial: 'dishes/index', locals: {dish: dish, menu: menu} %>
            </div>
          <% end %>
      </div>

    <% end %>
  </div>
    

</div>

app/views/menus/create.js.erb
$('#menu_name').val('');
$('.menu_index').prepend("<%= j render partial: '/menus/row', locals: {menu: @menu} %>");
$('.menuForm').fadeToggle();

app/views/menus/destroy.js.erb
$('#<%= dom_id(@menu) %>').fadeOut();

app/views/menus/edit.html.erb
<h1>Edit Menu</h1>

<%= simple_form_for [current_user, @menu] do |m| %> 
  <%= m.input :name %>
  <%= m.submit %>
<% end %>

app/views/menus/index.html.erb
<h1 class="restaurant_name"><%= @user.name.split.map(&:capitalize).join(' ') %></h1>

<% if user_signed_in? && (current_user == @user)  %>
  <a class="addMenu">New Menu</a><br><br>
    <div class="menuForm" style="display: none;">
      <%= render '/menus/new' %>
    </div>
<% else %>
  <a class="show_allergy"> Show all dishes </a>
<% end %>

<div class="menu_index">
  <% @menus.each do |menu| %> 
    <%= render partial: 'menus/row', locals: { menu: menu } %>
  <% end %>
</div>

app/views/menus/new.html.erb
<%= render "form" %>