config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  # second root. This route is used when user logs in
  get '/restaurants' => 'restaurants#index'
  get '/restaurants/favourites' => 'restaurants#favourite'

  # facebook callback
  get '/auth/:provider/callback' => 'sessions#create', as: :omni_auth

  # LOG IN
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # Add recipe to dish
  post '/dishes/:dish_id/add_recipe/:id' => 'recipes#add_recipe', as: :add_recipe 
  delete '/dishes/:dish_id/remove_recipe/:id' => 'recipes#remove_recipe', as: :remove_recipe


  resources :users do
    resources :favourites, only:[:create, :destroy] 
    resources :menus, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :menus, only:[] do
    resources :dishes
  end
  
  resources :recipes do
    resources :ingredients
  end 
  
  resources :preferences, only: [:show, :edit, :update]
  
  # takes out the ingredient to recipe but does not delete the ingredient itself
  delete '/recipes/:recipe_id/remove_ingredient/:ingredient_id/' => 'inclusions#destroy', as: :inclusion

  # like or unlike a dish
  post 'dish/:dish_id/add_like/:user_id' => 'likes#create', as: :like
  delete 'dish/:dish_id/remove_like/:user_id' => 'likes#destroy', as: :unlike
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  before_save :format_name
  has_many :inclusions, dependent: :nullify
  has_many :recipes, through: :inclusions, dependent: :nullify

  belongs_to :dish

  validates :name, presence: true

  def format_name
    self.name.downcase!
    self.name = self.name.singularize
  end

  def self.find_or_create(new_ingredient)
    ingredient = Ingredient.where(name: new_ingredient["name"].downcase.singularize, 
                                  category: new_ingredient["category"]).first
    unless ingredient
      ingredient = Ingredient.create(name: new_ingredient["name"],
                                     category: new_ingredient["category"])
    end
    ingredient
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  
  before_action :find_recipe, only: [ :new, :create, :edit, :update, :destroy]
  before_action :find_ingredient, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  
  def new
    @ingredient = @recipe.ingredients.new
  end

  def create
    ingredient = Ingredient.find_or_create(ingredient_params)
    if current_user.is_admin
      ingredient.recipes.push(@recipe)
      ingredient.save!
      redirect_to recipes_path
    else
      current_user.recipe.ingredients.push(ingredient)
      redirect_to preference_path(current_user.preference.id)
    end
  end

  def edit
  end

  def update
    if @ingredient.update ingredient_params
      redirect_to recipes_path
    else
      render :edit
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :category)
  end

  def find_recipe
    @recipe = Recipe.find params[:recipe_id]
  end

  def find_ingredient
    @ingredient = Ingredient.find params[:id]
  end

end

app/views/ingredients/_form.html.erb
<%= simple_form_for([@recipe, @ingredient], html: { class: 'form-horizontal' }) do |i|  %>
  <%= i.input :name %>
  <%= i.input :category, as: :radio_buttons, 
    collection: ["Beef", "Pork", "Poultry", "Seafood", "Wheat", "Vegetable", "Dairy/Eggs" ] %>
  <%= i.submit %>
<% end %>

app/views/ingredients/_index.html.erb
<button type="button" class="btn-link" data-toggle="modal" data-target="#<%= "#{dom_id(r)}-#{seed}" %>">
  Add an Ingredient
</button>
<div class="modal fade" id="<%= "#{dom_id(r)}-#{seed}" %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add an Ingredient</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @ingredient, url: recipe_ingredients_path(r) do |i| %>
          <%= i.input :name %>
          <%= i.input :category, as: :radio_buttons, 
                      collection: ["Beef", "Pork", "Poultry", "Seafood", "Grains/Wheat", "Vegetable", "Dairy/Eggs" ] %>
          <%= i.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Recipe ingredient table begins -->
<h4><%= r.name %> Ingredients</h4>

<table class="table table-striped" style="width:100%">
  <tr>
    <th>Ingredient</th>
    <th>Category</th> 
    <th></th>
  </tr>
  <% r.ingredients.each do |i| %>
    <tr>
      <td><%= i.name %></td>
      <td><%= i.category %></td> 
      <td>
        <%= link_to "Edit", edit_recipe_ingredient_path(r, i), class: "btn btn-default" %>
        <%= link_to "Delete this Ingredient", inclusion_path(r, i), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"  %>
      </td>
    </tr>
  <% end %>
</table>

app/views/ingredients/_substitution_modal.html.erb
<button type="button" class="btn-link" data-toggle="modal" data-target="#ingredient_<%= "#{dom_id(i)}-#{seed}" %>">
  Add a Substitute Ingredient
</button>
<div class="modal fade" id="ingredient_<%= "#{dom_id(i)}-#{seed}" %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add an Ingredient</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @substitute, url: substitute_ingredient_path(i) do |i| %>
          <%= i.input :name %>
          <%= i.input :category, as: :radio_buttons, 
                      collection: ["Beef", "Pork", "Poultry", "Seafood", "Grains/Wheat", "Vegetable", "Dairy/Eggs" ] %>
          <%= i.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<br>
<% i.substitution.each do |s| %>
  <%= s.name %>,
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient Page</h1> 
<%= render 'ingredients/form' %>

app/views/ingredients/new.html.erb
<%= render 'ingredients/form' %>