config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  # second root. This route is used when user logs in
  get '/restaurants' => 'restaurants#index'
  get '/restaurants/favourites' => 'restaurants#favourite'

  # facebook callback
  get '/auth/:provider/callback' => 'sessions#create', as: :omni_auth

  # LOG IN
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # Add recipe to dish
  post '/dishes/:dish_id/add_recipe/:id' => 'recipes#add_recipe', as: :add_recipe 
  delete '/dishes/:dish_id/remove_recipe/:id' => 'recipes#remove_recipe', as: :remove_recipe


  resources :users do
    resources :favourites, only:[:create, :destroy] 
    resources :menus, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :menus, only:[] do
    resources :dishes
  end
  
  resources :recipes do
    resources :ingredients
  end 
  
  resources :preferences, only: [:show, :edit, :update]
  
  # takes out the ingredient to recipe but does not delete the ingredient itself
  delete '/recipes/:recipe_id/remove_ingredient/:ingredient_id/' => 'inclusions#destroy', as: :inclusion

  # like or unlike a dish
  post 'dish/:dish_id/add_like/:user_id' => 'likes#create', as: :like
  delete 'dish/:dish_id/remove_like/:user_id' => 'likes#destroy', as: :unlike
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  # not being used?
  belongs_to :user
  belongs_to :menu

  has_many :likes
  has_many :liking_users, through: :likes, source: :user

  has_many :dish_recipes, dependent: :destroy
  has_many :recipes, through: :dish_recipes

  # has_many :menu_dishes, dependent: :destroy
  # has_many :menus, through: :menu_dishes, dependent: :destroy

  #added to make it easier to sesarch for all the ingredients of a dish
  has_many :ingredients, through: :recipes, dependent: :destroy

  validates :name, :price, presence: true
  # validates :name, uniqueness: { scope: :menu_dish }
  validates :description, length: {maximum: 100}
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  
  before_action :dish_id, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @menu = Menu.find params[:menu_id]
    @dish = @menu.dishes.new
  end
  
  # current user is used because the current user is always the owner of the menu
  # if the user does not own the menu, the buttons would not show
  # TODO: consider using a better alternative for current user. possibly 'owner'?
  def create
    @menu = Menu.find params[:menu_id]
    if @menu.dishes.create(dishes_params)
      redirect_to user_menus_path(current_user)
    else
      render :new
    end
  end

  def show
    @recipes = current_user.recipes.all
    @line = current_user.recipes.where(category: "Line")
    @dry = current_user.recipes.where(category: "Spices")
    @vin = current_user.recipes.where(category: "Vinaigrette")
    @sauce = current_user.recipes.where(category: "Sauce")
    @stew = current_user.recipes.where(category: "Stew")
    @other = current_user.recipes.where(category: "Other")
    @none = current_user.recipes.where(category: nil)
  end

  def edit
    @menu = Menu.find params[:menu_id]
  end

  def update
    @user = current_user
    @menu = Menu.find params[:menu_id]
    if @dish.update dishes_params
      redirect_to user_menus_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @menu = Menu.find params[:menu_id]
    @user = current_user
    @dish.destroy
    redirect_to user_menus_path(@user)
  end

  private
  def dishes_params
    params.require(:dish).permit(:name, :price, :description)
  end

  def dish_id
    @dish = Dish.find params[:id]
  end

  def menu_id
    @menu = Menu.find params[:menu_id]
  end
end

app/views/dishes/_index.html.erb
<div class="dish_title">
  <h4>
    <%= current_user == @user ? ( link_to dish.name, menu_dish_path(menu, dish) ): dish.name %>
  </h4>
</div>


<div class="like_container">
  <% if current_user.likes.map(&:dish_id).include?(dish.id) %>
    <p class="unlike" data-dish-id="<%= dish.id %>" data-user-id="<%= current_user.id %>">
      <a><span class="glyphicon glyphicon-star"></span></a>
    </p>
  <% else %>
    <p class="like" data-dish-id="<%= dish.id %>" data-user-id="<%= current_user.id %>">
      <a><span class="glyphicon glyphicon-star-empty"></span></a>
    </p>
  <% end %>
</div>



<p><%= dish.description %></p>
<p><%= dish.price %></p>

<div class="row">
  <div class="col-md-6">
    <% if dish.likes.count > 0 %>
      <p><%= dish.likes.count %> people like this dish!</p>
    <% end %>
  </div>

  <div class="col-md-6 dish_buttons">
    <% if user_signed_in? && (current_user.id == menu.user_id) %>
      <%= link_to "EDIT", edit_menu_dish_path(menu, dish) %> |
      <%= link_to "DELETE", menu_dish_path(menu, dish), method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  </div>
</div>

app/views/dishes/_recipes.html.erb
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#line" aria-controls="line" role="tab" data-toggle="tab">Line</a>
    </li>
    <li role="presentation">
      <a href="#spices" aria-controls="spices" role="tab" data-toggle="tab">Spices</a>
    </li>
    <li role="presentation">
      <a href="#vinaigrette" aria-controls="vinaigrette" role="tab" data-toggle="tab">Vinaigrette</a>
    </li>
    <li role="presentation">
      <a href="#sauce" aria-controls="sauce" role="tab" data-toggle="tab">Sauce</a>
    </li>
    <li role="presentation">
      <a href="#stew" aria-controls="stew" role="tab" data-toggle="tab">Stew</a>
    </li>
    <li role="presentation">
      <a href="#other" aria-controls="other" role="tab" data-toggle="tab">Other</a>
    </li>
    <li role="presentation">
      <a href="#all" aria-controls="other" role="tab" data-toggle="tab">All</a>
    </li>
</ul>

<div class="tab-content panel-group" role="tablist">
  <div role="tabpanel" class="tab-pane active" id="line">
    <% @line.each do |r| %>
      <% unless @dish.recipes.include?(r) %> 
        <div class="recipe_list" data-recipe-id="<%= r.id %>" data-name="<%= r.name %>" data-dish-id="<%= @dish.id %>"><%= r.name %></div>
      <% end %>
    <% end %>
  </div>
    <div role="tabpanel" class="tab-pane" id="spices">
    <% @dry.each do |r| %>
      <% unless @dish.recipes.include?(r) %> 
        <div class="recipe_list" data-recipe-id="<%= r.id %>" data-name="<%= r.name %>" data-dish-id="<%= @dish.id %>"><%= r.name %></div>
      <% end %>
    <% end %>
  </div>
  <div role="tabpanel" class="tab-pane" id="vinaigrette">
    <% @vin.each do |r| %>
      <% unless @dish.recipes.include?(r) %> 
        <div class="recipe_list" data-recipe-id="<%= r.id %>" data-name="<%= r.name %>" data-dish-id="<%= @dish.id %>"><%= r.name %></div>
      <% end %>
    <% end %>
  </div>
  <div role="tabpanel" class="tab-pane" id="sauce">
    <% @sauce.each do |r| %>
      <% unless @dish.recipes.include?(r) %> 
        <div class="recipe_list" data-recipe-id="<%= r.id %>" data-name="<%= r.name %>" data-dish-id="<%= @dish.id %>"><%= r.name %></div>
      <% end %>
    <% end %>
  </div>
  <div role="tabpanel" class="tab-pane" id="stew">
    <% @stew.each do |r| %>
      <% unless @dish.recipes.include?(r) %> 
        <div class="recipe_list" data-recipe-id="<%= r.id %>" data-name="<%= r.name %>" data-dish-id="<%= @dish.id %>"><%= r.name %></div>
      <% end %>
    <% end %>
  </div>
  <div role="tabpanel" class="tab-pane" id="other">
    <% @other.each do |r| %>
      <% unless @dish.recipes.include?(r) %> 
        <div class="recipe_list" data-recipe-id="<%= r.id %>" data-name="<%= r.name %>" data-dish-id="<%= @dish.id %>"><%= r.name %></div>
      <% end %>
    <% end %>
  </div>
  <div role="tabpanel" class="tab-pane" id="all">
    <% @recipes.each do |r| %>
      <% unless @dish.recipes.include?(r) %> 
        <div class="recipe_list" data-recipe-id="<%= r.id %>" data-name="<%= r.name %>" data-dish-id="<%= @dish.id %>"><%= r.name %></div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/dishes/edit.html.erb
<h2>Edit Dish Page</h2>

<%= simple_form_for([@menu, @dish], html: { class: 'form-horizontal' }) do |d| %>
  <%= d.input :name %>
  <%= d.input :description %>
  <%= d.input :price %>
  <%= d.submit %>
<% end %>

app/views/dishes/new.html.erb
<h2>New Dish Page</h2>

<%= simple_form_for @dish, url: menu_dishes_path(@menu) do |d| %>
  <%= d.input :name %>
  <%= d.input :description %>
  <%= d.input :price %>
  <%= d.submit %>
<% end %>

app/views/dishes/show.html.erb
<center>
  <h2><%= @dish.name %></h2>
  <p><%= @dish.description %></p>
  <p><%= @dish.price %></p><hr>
</center>
  
<div class="col-md-5">
  <h3><%= @dish.name %> Recipes</h3>
  <div class="dish_recipe_container">
    <% @dish.recipes.each do |dr| %>
      <div class="dish_recipes" data-recipe-id="<%= dr.id %>" data-name="<%= dr.name %>" data-dish-id="<%= @dish.id %>"><%= dr.name %></div>
    <% end %>
  </div>
</div>

<div class="col-md-7 recipe_list_container">
  <h3>Add from list of recipes</h3>
    <%= render 'dishes/recipes' %>
</div>