config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  # second root. This route is used when user logs in
  get '/restaurants' => 'restaurants#index'
  get '/restaurants/favourites' => 'restaurants#favourite'

  # facebook callback
  get '/auth/:provider/callback' => 'sessions#create', as: :omni_auth

  # LOG IN
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # Add recipe to dish
  post '/dishes/:dish_id/add_recipe/:id' => 'recipes#add_recipe', as: :add_recipe 
  delete '/dishes/:dish_id/remove_recipe/:id' => 'recipes#remove_recipe', as: :remove_recipe


  resources :users do
    resources :favourites, only:[:create, :destroy] 
    resources :menus, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :menus, only:[] do
    resources :dishes
  end
  
  resources :recipes do
    resources :ingredients
  end 
  
  resources :preferences, only: [:show, :edit, :update]
  
  # takes out the ingredient to recipe but does not delete the ingredient itself
  delete '/recipes/:recipe_id/remove_ingredient/:ingredient_id/' => 'inclusions#destroy', as: :inclusion

  # like or unlike a dish
  post 'dish/:dish_id/add_like/:user_id' => 'likes#create', as: :like
  delete 'dish/:dish_id/remove_like/:user_id' => 'likes#destroy', as: :unlike
end

app/views/layouts/_menu.html.erb
<div class="row menu_bar">
  <div class="menu_bar__logo col-md-2">
    PICKY EATER
  </div>
  <div class="menu_bar__links col-md-7">
    <% if current_user.is_admin != true %>
      <%= link_to "Preferences", preference_path(current_user.preference.id) %>
    <% else %>
      <%= link_to "View My Menus", user_menus_path(current_user) %>
      <%= link_to 'Recipes', recipes_path %>
    <% end %>
    <%= link_to 'Restaurants', restaurants_path %>
    <%= link_to "Favourites", '/restaurants/favourites' %>
  </div>

  <div class="col-md-3 menu_bar__user">
    Welcome <%= link_to current_user.name, user_path(current_user) %>
    <%= link_to "Logout", '/logout' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pie</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


</head>
<body>
<!-- flash -->
  <% if flash[:alert] %>
    <div class="flash__alert">
      <%= flash[:alert] %>
    </div>
  <% elsif flash[:notice] %>
    <div class="flash__notice">
      <%= flash[:notice] %>
    </div>
  <% end %>
<!-- flash ends -->

  <% if user_signed_in? %>
    <%= render 'layouts/menu' %>
  <% end %>

  <% if content_for(:sign_in) %>
    <%= yield (:sign_in)%>
  <% else %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  <% end %>

</body>
</html>